### ISSUE TITLE
TMC2208

### ISSUE THREAD

**Issue by Eforax** [davidramiro/Marlin-Ai3M#100]
Hi,

i want to upgrade to Marlin 1.1.9 after a few years now... I have changed 2 drivers to tmc2208 (X and Y) and turned the connection for this 2 . All is working fine. Wich version do i take now ? 3 original steppers and 2 of tmc2208. 

Thanks for every Tipps !

**Comment by davidramiro** [comment]
Just take the `stock_drivers` version.
