### ISSUE TITLE
[QUESTION] What precompiled to use for drives of two types

### ISSUE THREAD

**Issue by joseaguardia** [davidramiro/Marlin-Ai3M#112]
Hi!

I've TMC2208 on X and Y, and I already reversed the connectors. However, on Z and E I've the stock drivers.

What version should I use?

I've installed Marlin-AI3M-vx.x.x-TMC2208_reversed.hex but the printer doesn't work fine.

Thanks!

**Comment by davidramiro** [comment]
Use the stock driver binary.
