### ISSUE TITLE
Question: Will the precompilled hex file for TMC2208 drivers work using TMC2209 v2.0 drivers?

### ISSUE THREAD

**Issue by floatev** [davidramiro/Marlin-Ai3M#114]
I'm looking to upgrade from the stock drivers in the mega-s to the tcm2209. Anyone know if the pre-compilled hex file for TMC2208 drivers work with these drivers.? Or will I have to compile a new hex?
 
Thanks for reading!

My apologies if this isn't the correct place to ask. 

FloatEv

**Comment by davidramiro** [comment]
Judging by the Trinamic spec, they should be fully backwards compatible, so there should be no problem using that binary.

I'll close here for now, but if you do encounter any issues, I'd appreciate if you could report back.
