### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fltmssr** [davidramiro/Marlin-Ai3M#120]
After installing i3 Mega Marlin 1.1.9 Custom Firmware on my Anycubic i3 Mega S (bought like 2 months ago) I tried to print (SD-Card and USB) the Feeder Motor won´t rotate as intended. The prints (as far I Printed them) look like swiss cheese (see picture) I tried everything what in my perspective made sense (Change flow, speed, Temperature). As soon I had reset to the Original Firmware (i3Mega-Stock-V1.1.2.hex) everything works as it should. 
![20211017_105300](https://user-images.githubusercontent.com/92667752/137619968-dc58ad34-628f-4291-a901-20dec1b6af0c.jpg)

**Comment by davidramiro** [comment]
Please read this part of the installation guide: 

https://github.com/davidramiro/Marlin-Ai3M#after-obtaining-the-hex-file

You need to adjust those parameters if you have a Mega-S. That will solve your issue.
