### ISSUE TITLE
[BUG] M23 for file in folder give "open failed" error

### ISSUE THREAD

**Issue by fgiudice98** [davidramiro/Marlin-Ai3M#122]
As per title the M23 command (from pronterface, octoprint and others) for file in folder give "open failed" error, so cannot start a print from a file in a folder. I tried with different filenames for folders but without luck. The files work good when printing from lcd.

Below the pronterface console output

```
>>> M23 /TEST/PRINT_~1.GCO
SENDING:M23 /TEST/PRINT_~1.GCO
echo:Now fresh file: /TEST/PRINT_~1.GCO
open failed, File: PRINT_~1.GCO.
```

I am running the latest firmware on full stock Mega-S.

Another thing, is it possible to enable M33 command?

Thank in advance

**Comment by davidramiro** [comment]
Thanks for your contribution!
