### ISSUE TITLE
Settings for Release Build

### ISSUE THREAD

**Issue by polachz** [davidramiro/Marlin-AI3M#13]
Hallo.

Can you please provide settings or method how to build your various releases.:
- Default drivers
- TMC2208
- TMC2208 reversed.

I believe that it depends on some defines or somehow similar.

Can you please add this piece of information to Build own FW section of the Readme ?

Thank you.

**Comment by davidramiro** [comment]
Sure, will do!

**Comment by davidramiro** [comment]
Done 😊
