### ISSUE TITLE
Vref voltages on TMC2208 FAQ (E1 and E0 ?)

### ISSUE THREAD

**Issue by alessandrovarela** [davidramiro/Marlin-AI3M#130]
Hi.
I'm trying to adjust the Vref of my TCM2288 drivers for the Anycubic Mega S but I'm confused. In the [FAQ](https://github.com/davidramiro/Marlin-AI3M/wiki/Frequently-Asked-Questions#what-about-vref-voltages-on-tmc2208), it recommends voltages 1V on X, Z, E and 1.15V on Y and E0.
But I don't understand since for the Mega S we have the engines: X, Y, Left Z, Right Z and E0.
What would E1 referenced in the FAQ?
Thanks.

**Comment by davidramiro** [comment]
E1 is the second Z axis. E0 is the extruder. Not sure if they updated it, but on the PCB you can see that the driver for Z2 is actually labeled E1.
