### ISSUE TITLE
[BUG]Octo print manual bed level info not saving without SD card in

### ISSUE THREAD

**Issue by Orbit001** [davidramiro/Marlin-AI3M#133]
Hi, I am having issues with the manual bed leveling through octo print commands, I follow these (https://kore.cc/i3mega/doc/) instructions very closely, but when I save and start it again, it starts at the original location and does not save properly. Is it not saving because I don't have an SD plugged in? I have it connected to RPi4 instead.

**Comment by davidramiro** [comment]
The leveling process always starts at the 0Z position. Regardless of previous calibrations. This is not a bug, working as intended.
