### ISSUE TITLE
Count length of filament

### ISSUE THREAD

**Issue by druckgott** [davidramiro/Marlin-AI3M#24]
It will be nice if it's possible to implement am. Menupoint where it's possible to see how much filament is already used. It will be nice if you can calculate the mass so you could know how much it's availible on the rest of the filament roll and if it's enough  for the next print.

**Comment by davidramiro** [comment]
We can't edit the screen itself, other than adding some basic GCode commands to the SD menu.

That being said, I already enabled PRINTCOUNTER a long time ago (3c65df1a9770e161acca229817eba63d19c7fa79). You can use `M78` to show the total print time and filament length used. To reset it, e.g. on a new filament spool, you can use `M78 S78`.

Better yet, get OctoPrint and install [Filament Manager](https://plugins.octoprint.org/plugins/filamentmanager/).
