### ISSUE TITLE
[FR] IP-Address on display

### ISSUE THREAD

**Issue by thilbig** [davidramiro/Marlin-Ai3M#35]
Hi,
is there a way to show the IP-Address from Octoprint on the display?

Thomas

**Comment by davidramiro** [comment]
No, sorry. There are only a few hardcoded messages the display can show, like `Ready`, `Nozzle heating` and so on.

To get that functionality, you would need a regular Marlin compatible LCD display. Furthermore you would need to write a plugin for OctoPrint which then sends the IP address as M117 Gcode to show it on the screen.
