### ISSUE TITLE
[Docs] Error in "Calibration" wiki page

### ISSUE THREAD

**Issue by stecklars** [davidramiro/Marlin-Ai3M#36]
In the ["Calibration" wiki page](https://github.com/davidramiro/Marlin-AI3M/wiki/Calibration) the following is stated:

> If you use the stock cooler, I generally recommend running it at 70% (`M106 S191`) because of the 12V mod. Remember to also limit it in your slicer.

I think 75% would be correct here though? At least that is what the GCode would result in.

**Comment by davidramiro** [comment]
Correct. Hardly a bug though 🙂 Thanks for pointing it out.
