### ISSUE TITLE
termistor HT-NTC100K -  B3950

### ISSUE THREAD

**Issue by Worgak** [davidramiro/Marlin-Ai3M#41]
hi can i use this thermistor HT-NTC100K Thermistor Temperature Sensor for High Temperature Filament 350 Degrees Hotend Kit B3950, for your firmware

**Comment by davidramiro** [comment]
Yes, it will work but you might need to edit the thermistor type in Configuration.h. Please contact the manufacturer of your thermistor on which value to set the thermistor type setting at.

**Comment by Worgak** [comment]
thank you

**Comment by juanlu46** [comment]
@Worgak what thermal settings is? 11? 13? I bought the same sensor.

Thanks!
