### ISSUE TITLE
[QUESTION] Fans won't turn off, when printer is cooled down, still running

### ISSUE THREAD

**Issue by smart734** [davidramiro/Marlin-Ai3M#42]
**Describe the bug**
Hello, I have a question about the fans. After upgrading printer firmware, hotend and motherboard fan don't want to stop even if the printer is cooled down. I tried to load original firmware from anycubic, do M502, M500, but still same. Maybe I have higher temperature in room (25 - 26 C). I have now loaded Your firmware. Is possible to change, when will motherboard fan work? Thank you

**Printer (please complete the following information):**
 - Firmware version: [v1.4.6]
 - Printing method [SD]
 - Model [i3 Mega]

**M503 Output**
```
Connecting...
start
Printer is now online.
echo: External Reset
Marlin 1.1.9
Marlin-AI3M v1.4.6
echo: Last Updated: 2019-04-03 | Author: (davidramiro)
echo:Compiled: Apr  4 2019
echo: Free Memory: 1362  PlannerBufferBytes: 1664
echo:V55 stored settings retrieved (731 bytes; crc 3107)
echo:  G21    ; (mm)
echo:Filament settings: Disabled
echo:  M200 D1.75
echo:  M200 D0
echo:Steps per unit:
echo:  M92 X80.00 Y80.00 Z400.00 E92.60
echo:Maximum feedrates (units/s):
echo:  M203 X500.00 Y500.00 Z6.00 E60.00
echo:Maximum Acceleration (units/s2):
echo:  M201 X3000 Y2000 Z60 E10000
echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P1500.00 R3000.00 T3000.00
echo:Advanced: Q<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 Q20000 S0.00 T0.00 X10.00 Y10.00 Z0.40 E5.00
echo:Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:Mesh Bed Leveling:
echo:  M420 S0 Z0.00
echo:Endstop adjustment:
echo:  M666 Z0.00
echo:PID settings:
echo:  M301 P15.94 I1.17 D54.19
echo:  M304 P251.78 I49.57 D319.73
echo:Linear Advance:
echo:  M900 K0.00
echo:Filament load/unload lengths:
echo:  M603 L538.00 U555.00
echo:SD card ok
```

**Comment by davidramiro** [comment]
>I tried to load original firmware from anycubic, do M502, M500, but still same. 

Not a bug then 🙂

Actually, on the original firmware the motherboard fan is on all the time. On this firmware, it shuts off 60 seconds after the last motor movement.

The hotend fan behaves the same across the two firmwares, shutting off after the hotend has cooled down below 50°C.

If you experience the fans behaving in another way, there might be a broken fan transistor at play. Somewhat common on the Trigorilla board.
