### ISSUE TITLE
[BUG] compilation failure when enabling axis as TMC2208 (Uart mode)

### ISSUE THREAD

**Issue by Vertigo1206** [davidramiro/Marlin-Ai3M#53]
Hello,

Fist thanks for the great work you did.
Now I tried to change the Mode for the extruder from TMC2208_STANDALONE to TMC2208, cause I want to use this axis in UART mode.
changing line 565 to "#define E0_DRIVER_TYPE TMC2208 " in configurations.h

After that I always the the compiling error "'E0_SERIAL_RX_PIN' was not declared in this scope"
I added the TMC2208 library in Arduino IDE.

Please find attached the full log from the compiler.
[UART_compiler error.txt](https://github.com/davidramiro/Marlin-Ai3M/files/3790509/UART_compiler.error.txt)

**Comment by davidramiro** [comment]
Hey, 

you will need to add the pin(s) you use for UART communication to `pins_TRIGORILLA_14.h` like this:
```
#define E0_SERIAL_RX_PIN YY
#define E0_SERIAL_TX_PIN XX
```

I haven't used UART myself so I probably can't provide any further assistance, but at least compilation should go through smoothly when you do this!

**Comment by Vertigo1206** [comment]
Thanks for the fast response!
In my PCB stands V1.3, therefore i ignored "pins_TRIGORILLA_14.h"
I will try it and give feedback
