### ISSUE TITLE
[BUG] Anycubic i3 BLTouch Original Version 3.1 Problems please help

### ISSUE THREAD

**Issue by RedJohn14** [davidramiro/Marlin-Ai3M#68]
Hello,

I installed Marlin Build from your repo here: (v.1.1.9)
https://github.com/MNieddu91/Marlin-AI3M-BLTouch

My settings in configuration.h looks like this:
`//#define PROBE_MANUALLY
//#define MANUAL_PROBE_START_Z 0.2

/**

A Fix-Mounted Probe either doesn't deploy or needs manual deployment.
(e.g., an inductive probe or a nozzle-based probe-switch.)
*/
//#define FIX_MOUNTED_PROBE
/**

Z Servo Probe, such as an endstop switch on a rotating arm.
*/
//#define Z_PROBE_SERVO_NR 0 // Defaults to SERVO 0 connector.
//#define Z_SERVO_ANGLES {10,90} // Z Servo Deploy and Stow angles
/**

The BLTouch probe uses a Hall effect sensor and emulates a servo.
*/
define BLTOUCH
if ENABLED(BLTOUCH)
define BLTOUCH_DELAY 100 // (ms) Enable and increase if needed
/**

BLTouch V3.0 and newer smart series
For genuine BLTouch 3.0 sensors. Clones may be confused by 3.0 command angles. YMMV.
If the pin trigger is not detected, first try swapping the black and white wires then toggle this.
*/
//#define BLTOUCH_V3
#if ENABLED(BLTOUCH_V3)
#define BLTOUCH_FORCE_5V_MODE
#define BLTOUCH_FORCE_OPEN_DRAIN_MODE
#endif
#endif`
I used the original BLTouch v3.1 from here:
https://www.amazon.de/gp/product/B075B57CHD/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

I also tested your new repo Marlin 2.0.x:
https://github.com/MNieddu91/Marlin-Ai3M-2.0.x-BLTouch

I have home everything with G28 and use G29 all works perfekt. BLTouch Pin comes out but if I TRIGGERED it from hand nothing happens Z axis not stop!

If I home everything again with G28 and looks with M119 I see this:
< 13:10:36: x_min: TRIGGERED
< 13:10:36: y_min: TRIGGERED
< 13:10:36: z_min: TRIGGERED
< 13:10:36: z2_min: TRIGGERED
< 13:10:36: z_probe: open

The z_probe status won't change. I TRIGGERED the Pin manual but the status won't change. The Server cable on my motherboard is correct because I can use this command without any problem:

M280 P0 S10 ; pushes the pin down
M280 P0 S90 ; pulls the pin up
M280 P0 S120 ; Self test – keeps going until you do pin up/down or release alarm
M280 P0 S160 ; Release alarm

Only the trigger status will not work Z axis not stop! Any idea what the problem is?

Attached you find a picture from my BLTouch mount in the printers head. And a picture from the cable on my motherboard. I have the new Board 1.1.
![6D88CC47-D043-4364-8825-963F345A3D44](https://user-images.githubusercontent.com/47501883/71647809-0d047c80-2cfc-11ea-8d84-0bbe29e14a1b.jpeg)
![E06C17D8-ECAF-435F-B33A-D7F994F39D95](https://user-images.githubusercontent.com/47501883/71647810-0d047c80-2cfc-11ea-98c7-6233dc591de7.jpeg)i

**Comment by davidramiro** [comment]
>I installed Marlin Build from your repo here: (v.1.1.9)
>https://github.com/MNieddu91/Marlin-AI3M-BLTouch

That is not my repo. I don't have a BLtouch and my firmware doesn't support it, so I can't help you out here. Sorry.
