### ISSUE TITLE
Jerk control seems not working

### ISSUE THREAD

**Issue by elmacs** [davidramiro/Marlin-Ai3M#71]
I tried several xyzCalibrationCube with differents values of jerk
(M205 X10 Y10 ....  M205 X1 Y1) and the prints have just
the same ghost effect.

**Comment by davidramiro** [comment]
Which program do you use for slicing?

**Comment by elmacs** [comment]
I use Cura but I set and save the jerk with pronterface and then I edit the
file to ensure gcode jerk command is not present

Il mar 4 feb 2020, 14:25 David Ramiro <notifications@github.com> ha scritto:

**Comment by davidramiro** [comment]
I have just tested it myself and using extremely high and low jerk values, there is definitely a difference.

Ghosting is not just related to jerk, it's probably something else causing it.
