### ISSUE TITLE
[FR] Thingiverse page.

### ISSUE THREAD

**Issue by Flo082002** [davidramiro/Marlin-Ai3M#75]
Hi,
I noticed that the Thingiverse side of this firmware is broken since Makerbot changed the design.
The text is no longer displayed correctly and all images are missing.
Maybe it can be repaired.

![Screenshot_2020-03-25 Anycubic i3 Mega Mega-S Marlin 1 1 9 Custom Firmware - Extra Features Quality Tweaks by davidramiro](https://user-images.githubusercontent.com/27300374/77523392-f9455e00-6e85-11ea-9c10-725522634386.png)

https://www.thingiverse.com/thing:3249319
Best regards 
Florian S

**Comment by davidramiro** [comment]
Yup, seems like they broke Markdown formatting for texts this large. Nothing much I can do here. I tried moving it all into one section, eliminating the handy navigation bar, but it's still broken. 

Guess I'll have to create a page on my website and link that. Meh.

**Comment by davidramiro** [comment]
Done. It's not beautiful, but it gets the job done: https://kore.cc/i3mega/doc/

Thanks for bringing this to my attention!
