### ISSUE TITLE
[BUG] USB printing fails from Cura on Mega-S

### ISSUE THREAD

**Issue by kfsone** [davidramiro/Marlin-Ai3M#83]
Similiar to https://github.com/davidramiro/Marlin-Ai3M/issues/22 rel 1.4.6 will start printing from Cura over USB and then just stop somewhere on the first layer. Saving the gcode to sd card and printing from the card works fine,

**Comment by davidramiro** [comment]
I'd need some more info, log files, etc.

**Comment by kfsone** [comment]
Will collect a print this evening.

**Comment by kfsone** [comment]
Third print without doing it. Closing.
