### ISSUE TITLE
Mega-S - Extruder is reverse

### ISSUE THREAD

**Issue by murmelbahn** [davidramiro/Marlin-Ai3M#87]
Hi,

I just flashed my brandnew Mega-S with your awesome firmware. 
Sadly I have one problem. The extruder is running reverse. In the stock firmware everything works fine, the extruder is pulling the filament up but in the Marlin firmware the extruder is running reverse. I've compiled the firmware with the following changes:

Line 559 - 569

> //#define X_DRIVER_TYPE  TMC2208_STANDALONE // comment out for stock drivers
> //#define Y_DRIVER_TYPE  TMC2208_STANDALONE // comment out for stock drivers
> //#define Z_DRIVER_TYPE  TMC2208_STANDALONE // comment out for stock drivers
> #define X2_DRIVER_TYPE TMC2208_STANDALONE
> #define Y2_DRIVER_TYPE TMC2208_STANDALONE
> //#define Z2_DRIVER_TYPE TMC2208_STANDALONE // comment out for stock drivers
> //#define E0_DRIVER_TYPE TMC2208_STANDALONE // comment out for stock drivers
> //#define E1_DRIVER_TYPE TMC2208_STANDALONE // comment out for stock drivers
> #define E2_DRIVER_TYPE TMC2208_STANDALONE
> #define E3_DRIVER_TYPE TMC2208_STANDALONE
> #define E4_DRIVER_TYPE TMC2208_STANDALONE

Line 617:

`#define DEFAULT_AXIS_STEPS_PER_UNIT { 80, 80, 400, 384 }`

I think it has something to do with drivers above and I tried to not commenting them out and commenting everything out but without success. Maybe someone can give me an hint to solve this?

Thanks in advance!
And

**Comment by davidramiro** [comment]
Not a bug. As described in the [wiki](https://github.com/davidramiro/Marlin-AI3M/wiki/Customization-&-Compiling) you need to change the stepper driver directions as well. In your case, flip the boolean at https://github.com/davidramiro/Marlin-Ai3M/blob/master/Marlin/Configuration.h#L875 .
