### ISSUE TITLE
Question: What is the difference between the firmware versions

### ISSUE THREAD

**Issue by trunneml** [davidramiro/Marlin-Ai3M#89]
Hi,

what's the difference between: 
Marlin-AI3M-vx.x.x-TMC2208_reversed.hex
and 
Marlin-AI3M-vx.x.x-stock_drivers.hex

Are there any advantages or disadvantages using TMC2208_reversed?

What happens when the Marlin-AI3M-vx.x.x-TMC2208_reversed.hex is used with the stock stepper drivers?

Thanks for helping me.

Michael

**Comment by davidramiro** [comment]
If you use stock drivers, there is no advantage of using the TMC2208 version of the firmware. 

The binaries for TMC2208 have slightly tweaked timings and frequencies specifically for those drivers.  Just use the version that corresponds to your actual drivers.
