### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CageFox** [davidramiro/Marlin-Ai3M#92]
Hello! Nice work, excellent firmware, thank you!

Could you finally fix a long-standing mistake in your Calibration chapter?

https://github.com/davidramiro/Marlin-Ai3M/wiki/Calibration#pid-tuning

I receiving many yells from users who calibrate extruder steps by your manual. There is step:

"Put in the new value like this: M92 X80.00 Y80.00 Z400.00 Exxx.xx, replacing x with your value"

Could you fix this string?

First of all remove "X80.00 Y80.00" at all

And part "Z400.00 Exxx.xx" may be better to write it like "Zxxx.xx E0" ?

All the people using this manual step as it now will receive broken X steps

**Comment by davidramiro** [comment]
Fixed! Thanks for mentioning. Although X80 and Y80 is the stock value for i3 Mega and Mega-S, so most users have been fine with that command.
