### ISSUE TITLE
Tmc2209 

### ISSUE THREAD

**Issue by lillo68** [davidramiro/Marlin-Ai3M#94]
Can i install tmc2209? Which firmware should I use? Thanks so much

**Comment by davidramiro** [comment]
TMC2209 is working fine. Just use the TMC2208 firmware binaries.

**Comment by lillo68** [comment]
Ciao, David, i do not have reversed the connectors, can I use Marlin-AI3M-vx.x.x-TMC2208.hex or Marlin-AI3M-vx.x.x-TMC2208_reversed.hex.
Thanks so much!

**Comment by davidramiro** [comment]
Read the instructions. It's all there. Marlin-AI3M-vx.x.x-TMC2208.hex.
