### ISSUE TITLE
Filament runout sensor not pausing print

### ISSUE THREAD

**Issue by CTHobbit** [davidramiro/Marlin-Ai3M#95]
Using octoprint, but the filament runout sensor doesn't pause the print when there is no filament. I thought filament runout was still enabled on this version?

**Comment by davidramiro** [comment]
> I thought filament runout was still enabled on this version

It surely is. 

>Using octoprint

The filament sensor does not work with OctoPrint by default. Same as on the manufacturer firmware. USB printing simply has to be controlled from the host. There are plugins for this exact reason. You could connect the filament sensor with the GPIO pins of the Raspberry to have it working.
